groups:
  - name: prometheus_alerts
    rules:
    - alert: PrometheusConfigReloadFailed
      expr: prometheus_config_last_reload_successful == 0
      for: 3m
      labels:
        severity: warning
      annotations:
        description: Reloading Prometheus configuration has failed on {{ $labels.instance }}.
    - alert: PrometheusNotConnectedToAlertmanagers
      expr: prometheus_notifications_alert_managers_discovered < 1
      for: 5m
      labels:
        severity: warning
      annotations:
        description: Prometheus {{ $labels.instance }} is not connected to any Alertmanagers
