global:
  smtp_from: galushko.kp@gmail.com
  smtp_smarthost: smtp.gmail.com:587
  smtp_auth_username: galushko.kp@gmail.com
  smtp_auth_identity: galushko.kp@gmail.com
  smtp_auth_password: "mwzjnibkettpewnf"

templates:
- '/etc/alertmanager/template/*.tmpl'

route:
  group_by: ['instance']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: email
  routes:
  - match_re:
      severity: ^(critical|warning)$
    receiver: pager

receivers:
- name: email
  email_configs:
  - to: galushko.kp@gmail.com
- name: pager
  email_configs:
  - to: kgalushko@strij.tech
 




